sourcedatabase:
  type: mysql
  servers:
    - 192.168.0.1
    - 192.168.0.2
  user: root
  password: 123456
  name: test_db 
  tables:
    - xxx_info
    - yyy_info
targetdatabase:
  type: mysql
  servers:
    - 192.168.0.3
    - 192.168.0.4
  user: root
  password: abcdef
  name: target_db
  tables:
    - xxx_info_target
    - yyy_info_target
